# Generated by Django 6.0.6 on 2026-06-04 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolemenupermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolemenupermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='rolemenupermission',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='rolemenupermission',
            name='role',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='RoleMenuPermission',
        ),
    ]
