# Generated by Django 6.0.6 on 2026-06-05 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0002_remove_rolemenupermission_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ForeignKey(default='08138a02ae764be29754d3589a59e88f', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='sso_core.menu'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('menu', 'key')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='module',
        ),
    ]
