# Generated by Django 6.0.6 on 2026-06-10 (manual - based on actual DB state)

import django.db.models.deletion
from django.db import migrations, models


def fix_user_module_role(apps, schema_editor):
    """
    Actual DB state of user_module_role:
    - Has role_id (FK to role) AND role varchar(10) already
    - Has unique key on (user_id, module_id, role_id) — needs to change to (user_id, module_id)
    - role table: no menu_id column, has unique key on `key`
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET FOREIGN_KEY_CHECKS=0")

        # 1. Drop the old (user_id, module_id, role_id) unique key
        try:
            cursor.execute(
                "ALTER TABLE `user_module_role` "
                "DROP INDEX `user_module_role_user_module_role_uniq`"
            )
        except Exception:
            pass

        # 2. Drop role_id FK constraint
        try:
            cursor.execute(
                "ALTER TABLE `user_module_role` "
                "DROP FOREIGN KEY `user_module_role_role_id_c2cfe0f2_fk_role_id`"
            )
        except Exception:
            pass

        # 3. Drop role_id column
        try:
            cursor.execute("ALTER TABLE `user_module_role` DROP COLUMN `role_id`")
        except Exception:
            pass

        # 4. Add new unique key (user_id, module_id) if not exists
        try:
            cursor.execute(
                "ALTER TABLE `user_module_role` "
                "ADD UNIQUE KEY `user_module_role_user_id_module_id_uniq` (`user_id`, `module_id`)"
            )
        except Exception:
            pass  # already exists

        cursor.execute("SET FOREIGN_KEY_CHECKS=1")

        # 5. Drop role and menu tables
        try:
            cursor.execute("DROP TABLE IF EXISTS `menu`")
        except Exception:
            pass
        try:
            cursor.execute("DROP TABLE IF EXISTS `role`")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0004_fix_user_module_role_fk_to_user_matrix'),
    ]

    operations = [
        # 1. Register unmanaged ModuleMatrix in Django state (no DB change)
        migrations.CreateModel(
            name='ModuleMatrix',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('operator', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'db_table': 'module_matrix',
                'managed': False,
            },
        ),

        # 2. Do all real DB schema changes via Python
        migrations.RunPython(fix_user_module_role, migrations.RunPython.noop),

        # 3. Update Django state only (DB already correct after RunPython above)
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # UserModuleRole.module — add related_name
                migrations.AlterField(
                    model_name='usermodulerole',
                    name='module',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_roles',
                        to='sso_core.module',
                    ),
                ),
                # UserModuleRole.role — CharField
                migrations.AlterField(
                    model_name='usermodulerole',
                    name='role',
                    field=models.CharField(
                        choices=[('viewer', 'Viewer'), ('editor', 'Editor')],
                        default='viewer',
                        max_length=10,
                    ),
                ),
                # unique_together (user, module)
                migrations.AlterUniqueTogether(
                    name='usermodulerole',
                    unique_together={('user', 'module')},
                ),
                # User managed meta
                migrations.AlterModelOptions(
                    name='user',
                    options={'managed': False},
                ),
                # Remove Menu and Role from Django state
                migrations.DeleteModel(name='Menu'),
                migrations.DeleteModel(name='Role'),
            ],
        ),
    ]
