# Generated by Django 6.0.6 on 2026-06-10 03:17

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0005_simplify_role'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Add unique key to user_module_role on user_id and module_code
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE `user_module_role`
                        ADD UNIQUE KEY `user_module_role_user_id_module_code_uniq` (`user_id`, `module_code`);
                    """,
                    reverse_sql="""
                        ALTER TABLE `user_module_role`
                        DROP INDEX `user_module_role_user_id_module_code_uniq`;
                    """
                )
            ],
            state_operations=[
                # Update Django state: clear old unique_together
                migrations.AlterUniqueTogether(
                    name='usermodulerole',
                    unique_together=set(),
                ),
                # Add module_code to state
                migrations.AddField(
                    model_name='usermodulerole',
                    name='module_code',
                    field=models.ForeignKey(
                        db_column='module_code',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_roles',
                        to='sso_core.module',
                        to_field='code'
                    ),
                ),
                # Remove module from state
                migrations.RemoveField(
                    model_name='usermodulerole',
                    name='module',
                ),
                # Update Django state: set new unique_together
                migrations.AlterUniqueTogether(
                    name='usermodulerole',
                    unique_together={('user', 'module_code')},
                ),
                # Alter role on usermodulerole to include choices
                migrations.AlterField(
                    model_name='usermodulerole',
                    name='role',
                    field=models.CharField(
                        choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')],
                        default='viewer',
                        max_length=10
                    ),
                ),
                # Alter User model options
                migrations.AlterModelOptions(
                    name='user',
                    options={'managed': False},
                ),
            ]
        )
    ]
