# Generated by Django 6.0.6 on 2026-06-10 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0006_alter_usermodulerole_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodulerole',
            name='user',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='module_roles', to='sso_core.user', to_field='email'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='User Matrix',
        ),
    ]
