# Generated by Django 6.0.6 on 2026-06-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0007_alter_usermodulerole_user_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleMatrix',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'aw_user_role',
                'managed': False,
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Role',
                    fields=[
                        ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                        ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                        ('name', models.CharField(max_length=100)),
                        ('description', models.TextField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'aw_role',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='usermodulerole',
                    name='created_at',
                ),
                migrations.RemoveField(
                    model_name='usermodulerole',
                    name='is_active',
                ),
                migrations.RemoveField(
                    model_name='usermodulerole',
                    name='updated_at',
                ),
                migrations.AlterField(
                    model_name='usermodulerole',
                    name='id',
                    field=models.IntegerField(editable=False, primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),
    ]
