# Generated by Django 6.0.6 on 2026-06-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0008_rolematrix_role_remove_usermodulerole_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolematrix',
            table='aw_user_title',
        ),
    ]
