# Generated by Django 6.0.6 on 2026-07-03 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_core', '0009_alter_rolematrix_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('fname', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitleMatrix',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=50)),
                ('user', models.CharField(db_column='email', max_length=255)),
            ],
            options={
                'db_table': 'user_title_matrix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('login_method', models.CharField(choices=[('google', 'Google OAuth'), ('manual', 'Manual Login'), ('impersonate', 'Impersonate')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='RoleMatrix',
        ),
        migrations.AlterField(
            model_name='usermodulerole',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin'), ('approval', 'Approval')], default='viewer', max_length=10),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['email', '-created_at'], name='login_log_email_b750a4_idx'),
        ),
    ]
